version: '2'
services:
  sqlserver:
    image: microsoft/mssql-server-linux:2017-CU9-GDR2
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - SA_PASSWORD=Password!
     - MSSQL_AGENT_ENABLED=true
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - /opt/appdata/influxdb:/var/lib/influxdb
    restart:
      always
  grafana:
    image: grafana/grafana
    user: "0"
    container_name: grafana
    restart: always
    ports:
      - 3001:3000
    links:
     - influxdb
     - mysql  
    volumes:
      - /opt/appdata/grafana:/var/lib/grafana
    restart:
      always
