version: '2'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - /opt/appdata/influxdb:/var/lib/influxdb
    restart:
      always
  grafana:
    image: grafana/grafana
    user: "0"
    container_name: grafana
    restart: always
    ports:
      - 3001:3000
    volumes:
      - /opt/appdata/grafana:/var/lib/grafana
    restart:
      always